### ISSUE TITLE
Select Category showing BSON error 

### ISSUE THREAD

**Issue by ashisingh21** [techinfo-youtube/ecommerce-app-2023#1]
Hello,
After multiple attempts to solve the problem i am still unable to get what shoud i do to fix the error. I have matched the code several times, and there is no problem in it.

![image](https://user-images.githubusercontent.com/118272917/224165963-61d45111-369b-4df4-b98a-8e9a233cc7b4.png)

**Comment by techinfo-youtube** [comment]
I have fixed this issue please check final repository branch. I also explain this in later video
please also check model and category crud page
