### ISSUE TITLE
req.body

### ISSUE THREAD

**Issue by sakshi542** [techinfo-youtube/ecommerce-app-2023#21]
I am getting empty req.body  why so please help me!!.........there is not any problem with mongoDB connection. I guess the problem is with routing or parsing data . But somehow am not able to figure out.

**Comment by madgit11** [comment]
can you give the proper context that exactly where you getting thus error

**Comment by sakshi542** [comment]
when am making a post request to my register route through postman . am not receiving any data in my req.body . when am doing console.log(req.body) it is giving an empty list.

**Comment by sakshi542** [comment]
> can you give the proper context that exactly where you getting thus error

when am making a post request to my register route through postman . am not receiving any data in my req.body . when am doing console.log(req.body) it is giving an empty list.

**Comment by madgit11** [comment]
First check your registercontroller if there is any issue  or check the method you write post in your register.js

**Comment by sakshi542** [comment]
I have checked what have you said. I didn't find any problem there.
Can you please suggest something else?
My project has struck here since last few days.

**Comment by madgit11** [comment]
can you give me your code so that i can help you

**Comment by madgit11** [comment]
i wrote the code tell me if it is working or not

**Comment by sakshi542** [comment]
okay thank you for your help.
I figured out actually I didn't set my content type to application/json. Now it's not empty!!
